name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Context
        run: echo "The event name is ${{ github.event_name }}"
      - name: GitHub Information
        run: echo "The event name is ${{ toJSON(github) }}"

